# Generated by Django 5.2.3 on 2025-06-19 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='comments',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
