# Generated by Django 5.2.3 on 2025-06-20 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_article_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='createt_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='moment',
            old_name='image',
            new_name='photo',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='article_id',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='published',
        ),
        migrations.AddField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='article_comments', to='main.article'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
